# Generated by Django 6.0 on 2025-12-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logins',
            old_name='userid',
            new_name='userId',
        ),
    ]
